#!/bin/bash

#
# Sets up the build environment for perfkit
#

targets=" \
   build-essential \
   git-core \
   gnome-common \
   gtk-doc-tools \
   libglib2.0-dev
   libgtk2.0-dev \
   libclutter-gtk-0.10-dev \
   libdbus-glib-1-dev \
   libreadline-dev \
   "

# install required packages
sudo apt-get install $targets 

# checkout and install libethos
git clone git://git.dronelabs.com/ethos
pushd ethos
./autogen.sh
make
sudo make install
popd

# build perfkit
./autogen.sh
make
