#!/bin/bash

#
# Sets up the build environment for perfkit
#

targets=" \
   build-essential \
   gnome-common \
   gtk-doc-tools \
   libglib2.0-dev
   libgtk2.0-dev \
   libclutter-gtk-0.10-dev \
   libdbus-glib-1-dev \
   libreadline-dev \
   "

sudo apt-get install $targets 

./autogen.sh
make
