/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_dronelabs_Perfkit_SourceInfo
#define DBUS_GLIB_CLIENT_WRAPPERS_com_dronelabs_Perfkit_SourceInfo

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_dronelabs_Perfkit_SourceInfo_get_uid (DBusGProxy *proxy, char ** OUT_uid, GError **error)

{
  return dbus_g_proxy_call (proxy, "GetUid", error, G_TYPE_INVALID, G_TYPE_STRING, OUT_uid, G_TYPE_INVALID);
}

typedef void (*com_dronelabs_Perfkit_SourceInfo_get_uid_reply) (DBusGProxy *proxy, char * OUT_uid, GError *error, gpointer userdata);

static void
com_dronelabs_Perfkit_SourceInfo_get_uid_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_uid;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_uid, G_TYPE_INVALID);
  (*(com_dronelabs_Perfkit_SourceInfo_get_uid_reply)data->cb) (proxy, OUT_uid, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_dronelabs_Perfkit_SourceInfo_get_uid_async (DBusGProxy *proxy, com_dronelabs_Perfkit_SourceInfo_get_uid_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GetUid", com_dronelabs_Perfkit_SourceInfo_get_uid_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_dronelabs_Perfkit_SourceInfo_get_name (DBusGProxy *proxy, char ** OUT_name, GError **error)

{
  return dbus_g_proxy_call (proxy, "GetName", error, G_TYPE_INVALID, G_TYPE_STRING, OUT_name, G_TYPE_INVALID);
}

typedef void (*com_dronelabs_Perfkit_SourceInfo_get_name_reply) (DBusGProxy *proxy, char * OUT_name, GError *error, gpointer userdata);

static void
com_dronelabs_Perfkit_SourceInfo_get_name_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_name;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_name, G_TYPE_INVALID);
  (*(com_dronelabs_Perfkit_SourceInfo_get_name_reply)data->cb) (proxy, OUT_name, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_dronelabs_Perfkit_SourceInfo_get_name_async (DBusGProxy *proxy, com_dronelabs_Perfkit_SourceInfo_get_name_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GetName", com_dronelabs_Perfkit_SourceInfo_get_name_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_dronelabs_Perfkit_SourceInfo_create (DBusGProxy *proxy, char** OUT_path, GError **error)

{
  return dbus_g_proxy_call (proxy, "Create", error, G_TYPE_INVALID, DBUS_TYPE_G_OBJECT_PATH, OUT_path, G_TYPE_INVALID);
}

typedef void (*com_dronelabs_Perfkit_SourceInfo_create_reply) (DBusGProxy *proxy, char *OUT_path, GError *error, gpointer userdata);

static void
com_dronelabs_Perfkit_SourceInfo_create_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char* OUT_path;
  dbus_g_proxy_end_call (proxy, call, &error, DBUS_TYPE_G_OBJECT_PATH, &OUT_path, G_TYPE_INVALID);
  (*(com_dronelabs_Perfkit_SourceInfo_create_reply)data->cb) (proxy, OUT_path, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_dronelabs_Perfkit_SourceInfo_create_async (DBusGProxy *proxy, com_dronelabs_Perfkit_SourceInfo_create_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Create", com_dronelabs_Perfkit_SourceInfo_create_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_dronelabs_Perfkit_SourceInfo */

G_END_DECLS
