/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_dronelabs_Perfkit_Sources
#define DBUS_GLIB_CLIENT_WRAPPERS_com_dronelabs_Perfkit_Sources

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_dronelabs_Perfkit_Sources_get_source_types (DBusGProxy *proxy, char *** OUT_paths, GError **error)

{
  return dbus_g_proxy_call (proxy, "GetSourceTypes", error, G_TYPE_INVALID, G_TYPE_STRV, OUT_paths, G_TYPE_INVALID);
}

typedef void (*com_dronelabs_Perfkit_Sources_get_source_types_reply) (DBusGProxy *proxy, char * *OUT_paths, GError *error, gpointer userdata);

static void
com_dronelabs_Perfkit_Sources_get_source_types_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char ** OUT_paths;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRV, &OUT_paths, G_TYPE_INVALID);
  (*(com_dronelabs_Perfkit_Sources_get_source_types_reply)data->cb) (proxy, OUT_paths, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_dronelabs_Perfkit_Sources_get_source_types_async (DBusGProxy *proxy, com_dronelabs_Perfkit_Sources_get_source_types_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GetSourceTypes", com_dronelabs_Perfkit_Sources_get_source_types_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_dronelabs_Perfkit_Sources */

G_END_DECLS
