/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_dronelabs_Perfkit_Source
#define DBUS_GLIB_CLIENT_WRAPPERS_com_dronelabs_Perfkit_Source

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_dronelabs_Perfkit_Source_set_channel (DBusGProxy *proxy, const char * IN_path, GError **error)

{
  return dbus_g_proxy_call (proxy, "SetChannel", error, G_TYPE_STRING, IN_path, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*com_dronelabs_Perfkit_Source_set_channel_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
com_dronelabs_Perfkit_Source_set_channel_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(com_dronelabs_Perfkit_Source_set_channel_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_dronelabs_Perfkit_Source_set_channel_async (DBusGProxy *proxy, const char * IN_path, com_dronelabs_Perfkit_Source_set_channel_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "SetChannel", com_dronelabs_Perfkit_Source_set_channel_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_path, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_dronelabs_Perfkit_Source_get_channel (DBusGProxy *proxy, char ** OUT_path, GError **error)

{
  return dbus_g_proxy_call (proxy, "GetChannel", error, G_TYPE_INVALID, G_TYPE_STRING, OUT_path, G_TYPE_INVALID);
}

typedef void (*com_dronelabs_Perfkit_Source_get_channel_reply) (DBusGProxy *proxy, char * OUT_path, GError *error, gpointer userdata);

static void
com_dronelabs_Perfkit_Source_get_channel_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_path;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_path, G_TYPE_INVALID);
  (*(com_dronelabs_Perfkit_Source_get_channel_reply)data->cb) (proxy, OUT_path, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_dronelabs_Perfkit_Source_get_channel_async (DBusGProxy *proxy, com_dronelabs_Perfkit_Source_get_channel_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GetChannel", com_dronelabs_Perfkit_Source_get_channel_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_dronelabs_Perfkit_Source */

G_END_DECLS
